import { NextResponse } from 'next/server';
import { Product } from '@/store/useStore';

const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Chrono Onyx Watch',
    description: 'A masterpiece of minimalism. Featuring a matte-black stainless steel case, sapphire crystal glass, and a precision Japanese quartz movement. Built for the modern pioneer.',
    price: 245,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 124,
    sizes: ['40mm', '44mm'],
    colors: ['Obsidian Black', 'Gold Accents', 'Space Grey'],
    features: ['Sapphire crystal lens', '5 ATM Water resistance', '316L Stainless steel case', '2-year warranty'],
    inStock: true,
  },
  {
    id: 'prod-2',
    name: 'Stealth Knit Sneakers',
    description: 'Engineered for absolute weightlessness and supreme comfort. Features a breathable recycled knit upper, a responsive custom foam sole, and clean geometric silhouette.',
    price: 135,
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 312,
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    colors: ['Triple Black', 'Ghost White', 'Crimson Edge'],
    features: ['Recycled knit upper', 'High-rebound EVA outsole', 'Reflective detailing', 'Sock-like snug fit'],
    inStock: true,
  },
  {
    id: 'prod-3',
    name: 'Obsidian Commuter Backpack',
    description: 'The ultimate weather-resistant carry-all. Designed with an armored technical shell, a dedicated 16-inch lay-flat laptop sleeve, and smart organizational pockets for daily commutes.',
    price: 180,
    category: 'Gear',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 98,
    sizes: ['24 Liters', '32 Liters'],
    colors: ['Matte Black', 'Dark Olive'],
    features: ['Cordura® ballistic nylon', 'YKK® AquaGuard® zippers', 'Hidden passport pocket', 'Luggage pass-through'],
    inStock: true,
  },
  {
    id: 'prod-4',
    name: 'Charcoal Bomber Jacket',
    description: 'A modern iteration of a military classic. Tailored from a premium water-repellent nylon shell, micro-fleece lining, and double-knit ribbed trims for structured warmth.',
    price: 210,
    category: 'Apparel',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 86,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal Grey', 'Midnight Navy'],
    features: ['Water-resistant shell', 'Polyester fill insulation', 'Utility sleeve pocket', 'Heavy-duty zip front'],
    inStock: true,
  },
  {
    id: 'prod-5',
    name: 'Premium Leather Cardholder',
    description: 'Handcrafted from full-grain Tuscan vegetable-tanned leather. Features four card slots and a central bill pocket. Designed to develop a rich unique patina over time.',
    price: 65,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1689844833510-10939e60e8dc?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    rating: 4.6,
    reviewsCount: 142,
    colors: ['Tan Leather', 'Obsidian Black', 'Cognac Brown'],
    features: ['Full-grain Tuscan leather', 'RFID blocking lining', 'Hand-stitched edges', 'Slim 4mm profile'],
    inStock: true,
  },
  {
    id: 'prod-6',
    name: 'Minimalist Oversized Hoodie',
    description: 'Woven from custom ultra-dense 480GSM organic cotton French terry. Features a double-lined hood without drawstrings, dropped shoulders, and a relaxed, structured drape.',
    price: 110,
    category: 'Apparel',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 203,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bone White', 'Concrete Grey', 'Black Onyx'],
    features: ['100% Organic Cotton', 'Heavyweight 480GSM fabric', 'Pre-shrunk', 'No-drawstring clean hood'],
    inStock: true,
  },
  {
    id: 'prod-7',
    name: 'Nomad Suede Chelsea Boots',
    description: 'An elegant slip-on boot crafted from water-repellent Italian suede leather. Finished with an all-weather crepe sole and comfortable elasticated side gussets.',
    price: 220,
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 64,
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    colors: ['Sand Suede', 'Dark Brown Suede'],
    features: ['Premium Italian suede', 'Natural rubber crepe sole', 'Breathable leather lining', 'Reinforced heel pull-tab'],
    inStock: false, // Out of stock to test out-of-stock badge / state
  },
  {
    id: 'prod-8',
    name: 'Hydro-Thermal Flask',
    description: 'Double-wall vacuum insulated flask designed to keep your drinks ice-cold for 24 hours or piping hot for 12. Complete with a sweat-proof matte finish.',
    price: 45,
    category: 'Gear',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=600&auto=format&fit=crop',
    rating: 4.5,
    reviewsCount: 418,
    sizes: ['18 oz', '32 oz'],
    colors: ['Obsidian Black', 'Alabaster White', 'Pacific Blue'],
    features: ['18/8 Pro-grade stainless steel', 'BPA-free & Phthalate-free', 'TempShield™ insulation', 'Leakproof Flex Cap'],
    inStock: true,
  }
];

export async function GET() {
  // Simulate network latency
  await new Promise((resolve) => setTimeout(resolve, 800));

  return NextResponse.json(MOCK_PRODUCTS);
}
